/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";
import * as BitadventurerApi from "../../../index";

export declare namespace Store {
    interface Options {
        environment?: core.Supplier<environments.BitadventurerApiEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the api_key header */
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the api_key header */
        apiKey?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Access to Petstore orders
 */
export class Store {
    constructor(protected readonly _options: Store.Options) {}

    /**
     * Returns a map of status codes to quantities
     *
     * @param {Store.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.store.getInventory()
     */
    public getInventory(requestOptions?: Store.RequestOptions): core.APIPromise<Record<string, number>> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "store/inventory"
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.store.getInventory.Response.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.BitadventurerApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling GET /store/inventory."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * Place a new order in the store
     *
     * @param {BitadventurerApi.Order} request
     * @param {Store.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.MethodNotAllowedError}
     *
     * @example
     *     await client.store.placeOrder({})
     */
    public placeOrder(
        request: BitadventurerApi.Order,
        requestOptions?: Store.RequestOptions
    ): core.APIPromise<BitadventurerApi.Order> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "store/order"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/x-www-form-urlencoded",
                    requestType: "json",
                    body: serializers.Order.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.Order.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 405:
                            throw new BitadventurerApi.MethodNotAllowedError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling POST /store/order."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
     *
     * @param {number} orderId - ID of order that needs to be fetched
     * @param {Store.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.BadRequestError}
     * @throws {@link BitadventurerApi.NotFoundError}
     *
     * @example
     *     await client.store.getOrderById(1000000)
     */
    public getOrderById(
        orderId: number,
        requestOptions?: Store.RequestOptions
    ): core.APIPromise<BitadventurerApi.Order> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        `store/order/${encodeURIComponent(orderId)}`
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.Order.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new BitadventurerApi.BadRequestError(_response.error.body);
                        case 404:
                            throw new BitadventurerApi.NotFoundError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling GET /store/order/{orderId}."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
     *
     * @param {number} orderId - ID of the order that needs to be deleted
     * @param {Store.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.BadRequestError}
     * @throws {@link BitadventurerApi.NotFoundError}
     *
     * @example
     *     await client.store.deleteOrder(1000000)
     */
    public deleteOrder(orderId: number, requestOptions?: Store.RequestOptions): core.APIPromise<void> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        `store/order/${encodeURIComponent(orderId)}`
                    ),
                    method: "DELETE",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: undefined,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new BitadventurerApi.BadRequestError(_response.error.body);
                        case 404:
                            throw new BitadventurerApi.NotFoundError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling DELETE /store/order/{orderId}."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
