/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BitadventurerApi from "../../../../api/index";
import * as core from "../../../../core";

export const FindPetsByStatusRequestStatus: core.serialization.Schema<
    serializers.FindPetsByStatusRequestStatus.Raw,
    BitadventurerApi.FindPetsByStatusRequestStatus
> = core.serialization.enum_(["available", "pending", "sold"]);

export declare namespace FindPetsByStatusRequestStatus {
    type Raw = "available" | "pending" | "sold";
}
