/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as BitadventurerApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace User {
    interface Options {
        environment?: core.Supplier<environments.BitadventurerApiEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the api_key header */
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the api_key header */
        apiKey?: string;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

/**
 * Operations about user
 */
export class User {
    constructor(protected readonly _options: User.Options) {}

    /**
     * This can only be done by the logged in user.
     *
     * @param {BitadventurerApi.User} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.createUser({})
     */
    public createUser(
        request: BitadventurerApi.User,
        requestOptions?: User.RequestOptions
    ): core.APIPromise<BitadventurerApi.User> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "user"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/x-www-form-urlencoded",
                    requestType: "json",
                    body: serializers.User.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.User.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.BitadventurerApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError("Timeout exceeded when calling POST /user.");
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * Creates list of users with given input array
     *
     * @param {BitadventurerApi.User[]} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.createUsersWithListInput([{}])
     */
    public createUsersWithListInput(
        request: BitadventurerApi.User[],
        requestOptions?: User.RequestOptions
    ): core.APIPromise<BitadventurerApi.User> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "user/createWithList"
                    ),
                    method: "POST",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    body: serializers.user.createUsersWithListInput.Request.jsonOrThrow(request, {
                        unrecognizedObjectKeys: "strip",
                    }),
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.User.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.BitadventurerApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling POST /user/createWithList."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     *
     *
     * @param {BitadventurerApi.LoginUserRequest} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.BadRequestError}
     *
     * @example
     *     await client.user.loginUser()
     */
    public loginUser(
        request: BitadventurerApi.LoginUserRequest = {},
        requestOptions?: User.RequestOptions
    ): core.APIPromise<string> {
        return core.APIPromise.from(
            (async () => {
                const { username, password } = request;
                const _queryParams: Record<string, string | string[] | object | object[]> = {};
                if (username != null) {
                    _queryParams["username"] = username;
                }
                if (password != null) {
                    _queryParams["password"] = password;
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "user/login"
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.user.loginUser.Response.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new BitadventurerApi.BadRequestError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError("Timeout exceeded when calling GET /user/login.");
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     *
     *
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.logoutUser()
     */
    public logoutUser(requestOptions?: User.RequestOptions): core.APIPromise<void> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        "user/logout"
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: undefined,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.BitadventurerApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling GET /user/logout."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     *
     *
     * @param {string} username - The name that needs to be fetched. Use user1 for testing.
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.BadRequestError}
     * @throws {@link BitadventurerApi.NotFoundError}
     *
     * @example
     *     await client.user.getUserByName("username")
     */
    public getUserByName(
        username: string,
        requestOptions?: User.RequestOptions
    ): core.APIPromise<BitadventurerApi.User> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        `user/${encodeURIComponent(username)}`
                    ),
                    method: "GET",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: serializers.User.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new BitadventurerApi.BadRequestError(_response.error.body);
                        case 404:
                            throw new BitadventurerApi.NotFoundError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling GET /user/{username}."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * This can only be done by the logged in user.
     *
     * @param {string} username - name that needs to be updated
     * @param {BitadventurerApi.User} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.updateUser("username", {})
     */
    public updateUser(
        username: string,
        request: BitadventurerApi.User,
        requestOptions?: User.RequestOptions
    ): core.APIPromise<void> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        `user/${encodeURIComponent(username)}`
                    ),
                    method: "PUT",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/x-www-form-urlencoded",
                    requestType: "json",
                    body: serializers.User.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: undefined,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.BitadventurerApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling PUT /user/{username}."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    /**
     * This can only be done by the logged in user.
     *
     * @param {string} username - The name that needs to be deleted
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BitadventurerApi.BadRequestError}
     * @throws {@link BitadventurerApi.NotFoundError}
     *
     * @example
     *     await client.user.deleteUser("username")
     */
    public deleteUser(username: string, requestOptions?: User.RequestOptions): core.APIPromise<void> {
        return core.APIPromise.from(
            (async () => {
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.environment)) ??
                            environments.BitadventurerApiEnvironment.Default,
                        `user/${encodeURIComponent(username)}`
                    ),
                    method: "DELETE",
                    headers: {
                        Authorization: await this._getAuthorizationHeader(),
                        api_key: await core.Supplier.get(this._options.apiKey),
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "fern-swagger-petstore",
                        "X-Fern-SDK-Version": "0.0.316",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        ok: _response.ok,
                        body: undefined,
                        headers: _response.headers,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new BitadventurerApi.BadRequestError(_response.error.body);
                        case 404:
                            throw new BitadventurerApi.NotFoundError(_response.error.body);
                        default:
                            throw new errors.BitadventurerApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.BitadventurerApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                        });
                    case "timeout":
                        throw new errors.BitadventurerApiTimeoutError(
                            "Timeout exceeded when calling DELETE /user/{username}."
                        );
                    case "unknown":
                        throw new errors.BitadventurerApiError({
                            message: _response.error.errorMessage,
                        });
                }
            })()
        );
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
