/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FindPetsByStatusRequestStatus = "available" | "pending" | "sold";

export const FindPetsByStatusRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
