/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BitadventurerApi from "../index";

export interface Customer {
    id?: number;
    username?: string;
    address?: BitadventurerApi.Address[];
}
