/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Order Status
 */
export type OrderStatus = "placed" | "approved" | "delivered";

export const OrderStatus = {
    Placed: "placed",
    Approved: "approved",
    Delivered: "delivered",
} as const;
