/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BitadventurerApi from "../index";

export interface Order {
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: Date;
    /** Order Status */
    status?: BitadventurerApi.OrderStatus;
    complete?: boolean;
}
