/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BitadventurerApi from "../index";

export interface Pet {
    id?: number;
    name: string;
    category?: BitadventurerApi.Category;
    photoUrls: string[];
    tags?: BitadventurerApi.Tag[];
    /** pet status in the store */
    status?: BitadventurerApi.PetStatus;
}
