/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * pet status in the store
 */
export type PetStatus = "available" | "pending" | "sold";

export const PetStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
