/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BitadventurerApi from "../../../../api/index";
import * as core from "../../../../core";
import { Pet } from "../../../types/Pet";

export const Response: core.serialization.Schema<
    serializers.pet.findPetsByStatus.Response.Raw,
    BitadventurerApi.Pet[]
> = core.serialization.list(Pet);

export declare namespace Response {
    type Raw = Pet.Raw[];
}
