/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BitadventurerApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface FindPetsByStatusRequest {
    /**
     * Status values that need to be considered for filter
     */
    status?: BitadventurerApi.FindPetsByStatusRequestStatus;
}
