/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const ApiResponse: core.serialization.ObjectSchema<serializers.ApiResponse.Raw, BitadventurerApi.ApiResponse> =
    core.serialization.object({
        code: core.serialization.number().optional(),
        type: core.serialization.string().optional(),
        message: core.serialization.string().optional(),
    });

export declare namespace ApiResponse {
    interface Raw {
        code?: number | null;
        type?: string | null;
        message?: string | null;
    }
}
