/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const Category: core.serialization.ObjectSchema<serializers.Category.Raw, BitadventurerApi.Category> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace Category {
    interface Raw {
        id?: number | null;
        name?: string | null;
    }
}
