/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";
import { Address } from "./Address";

export const Customer: core.serialization.ObjectSchema<serializers.Customer.Raw, BitadventurerApi.Customer> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        username: core.serialization.string().optional(),
        address: core.serialization.list(Address).optional(),
    });

export declare namespace Customer {
    interface Raw {
        id?: number | null;
        username?: string | null;
        address?: Address.Raw[] | null;
    }
}
