/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, BitadventurerApi.OauthScope> =
    core.serialization.enum_(["write:pets", "read:pets"]);

export declare namespace OauthScope {
    type Raw = "write:pets" | "read:pets";
}
