/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";
import { OrderStatus } from "./OrderStatus";

export const Order: core.serialization.ObjectSchema<serializers.Order.Raw, BitadventurerApi.Order> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        petId: core.serialization.number().optional(),
        quantity: core.serialization.number().optional(),
        shipDate: core.serialization.date().optional(),
        status: OrderStatus.optional(),
        complete: core.serialization.boolean().optional(),
    });

export declare namespace Order {
    interface Raw {
        id?: number | null;
        petId?: number | null;
        quantity?: number | null;
        shipDate?: string | null;
        status?: OrderStatus.Raw | null;
        complete?: boolean | null;
    }
}
