/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";
import { Category } from "./Category";
import { Tag } from "./Tag";
import { PetStatus } from "./PetStatus";

export const Pet: core.serialization.ObjectSchema<serializers.Pet.Raw, BitadventurerApi.Pet> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string(),
        category: Category.optional(),
        photoUrls: core.serialization.list(core.serialization.string()),
        tags: core.serialization.list(Tag).optional(),
        status: PetStatus.optional(),
    });

export declare namespace Pet {
    interface Raw {
        id?: number | null;
        name: string;
        category?: Category.Raw | null;
        photoUrls: string[];
        tags?: Tag.Raw[] | null;
        status?: PetStatus.Raw | null;
    }
}
