/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const PetStatus: core.serialization.Schema<serializers.PetStatus.Raw, BitadventurerApi.PetStatus> =
    core.serialization.enum_(["available", "pending", "sold"]);

export declare namespace PetStatus {
    type Raw = "available" | "pending" | "sold";
}
