/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const Tag: core.serialization.ObjectSchema<serializers.Tag.Raw, BitadventurerApi.Tag> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace Tag {
    interface Raw {
        id?: number | null;
        name?: string | null;
    }
}
