/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BitadventurerApi from "../../api/index";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, BitadventurerApi.User> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        username: core.serialization.string().optional(),
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        password: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
        userStatus: core.serialization.number().optional(),
    });

export declare namespace User {
    interface Raw {
        id?: number | null;
        username?: string | null;
        firstName?: string | null;
        lastName?: string | null;
        email?: string | null;
        password?: string | null;
        phone?: string | null;
        userStatus?: number | null;
    }
}
