/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BitadventurerApi from "../../../../api/index";
import * as core from "../../../../core";
import { User } from "../../../types/User";

export const Request: core.serialization.Schema<
    serializers.user.createUsersWithListInput.Request.Raw,
    BitadventurerApi.User[]
> = core.serialization.list(User);

export declare namespace Request {
    type Raw = User.Raw[];
}
