/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const BitadventurerApiEnvironment = {
    Default: "/api/v3",
} as const;

export type BitadventurerApiEnvironment = typeof BitadventurerApiEnvironment.Default;
